### ISSUE TITLE
大哥我在复现你的作品

### ISSUE THREAD

**Issue by luotianhang** [hatsuame/LineDistiller#9]
我想请问你的数据集准备多大，训练多久，batchsize多少。且没有这个模型的前提下，你是如何制作数据集的。谢谢大哥

**Comment by hepesu** [comment]
1. 数据集准备多大
数据集 基本拟合20-100张
公开的模型也是用大约这个数据量的数据集训练的
由于画面原来就存在线，所以任务相对简单，不需要数据多；如果要训练画面中线不明显的，数据量就要大比较多

2. 训练多久，batchsize多少
参数见Train.py， 约10 epochs（5120个数据增强产生的样本）拟合
EPOCHS = 25
BATCH_SIZE = 4
steps_per_epoch=512 // BATCH_SIZE, 

3. 你是如何制作数据集的
人工标记的
